/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module Lut(a, b, clk, reset, s, sync, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  input clk;
  wire clk;
  output [4:0] out;
  wire [4:0] out;
  wire [4:0] out_reg;
  input reset;
  wire reset;
  input [1:0] s;
  wire [1:0] s;
  input sync;
  wire sync;
  wire [4:0] y;
  sky130_fd_sc_hd__clkinv_1 _055_ (
    .A(a[2]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _056_ (
    .A(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor2_1 _057_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _058_ (
    .A(b[3]),
    .B(a[3]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _059_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__xnor2_1 _060_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _061_ (
    .A(a[1]),
    .SLEEP(b[1]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _062_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _063_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__xnor2_1 _064_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _065_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _066_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__nand2b_1 _067_ (
    .A_N(a[0]),
    .B(b[0]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__a21oi_1 _068_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_010_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _069_ (
    .A(_009_),
    .SLEEP(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__maj3_1 _070_ (
    .A(b[2]),
    .B(_005_),
    .C(_017_),
    .X(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _071_ (
    .A(s[0]),
    .B(s[1]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _072_ (
    .A(_007_),
    .B(_019_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _073_ (
    .A(_013_),
    .SLEEP(_014_),
    .X(_022_)
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(_012_),
    .A2(_014_),
    .B1(_011_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2b_1 _075_ (
    .A_N(_009_),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__maj3_1 _076_ (
    .A(b[2]),
    .B(a[2]),
    .C(_023_),
    .X(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _077_ (
    .A(s[1]),
    .SLEEP(s[0]),
    .X(_026_)
  );
  sky130_fd_sc_hd__xor2_1 _078_ (
    .A(_007_),
    .B(_025_),
    .X(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _079_ (
    .A1(b[3]),
    .A2(a[3]),
    .B1(s[0]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _080_ (
    .A(s[1]),
    .B(_006_),
    .C(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a21oi_1 _081_ (
    .A1(_026_),
    .A2(_027_),
    .B1(_029_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__o21ai_0 _082_ (
    .A1(_020_),
    .A2(_021_),
    .B1(_030_),
    .Y(y[3])
  );
  sky130_fd_sc_hd__nor2b_1 _083_ (
    .A(_009_),
    .B_N(_017_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand3_1 _084_ (
    .A(_009_),
    .B(_011_),
    .C(_022_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _085_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(s[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _086_ (
    .A(s[1]),
    .B(_008_),
    .C(_033_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__a31oi_1 _087_ (
    .A1(_024_),
    .A2(_026_),
    .A3(_032_),
    .B1(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__o31ai_1 _088_ (
    .A1(_018_),
    .A2(_020_),
    .A3(_031_),
    .B1(_035_),
    .Y(y[2])
  );
  sky130_fd_sc_hd__nor2_1 _089_ (
    .A(_013_),
    .B(_016_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__a21o_1 _090_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_020_),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _091_ (
    .A(_013_),
    .B(_014_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _092_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(s[0]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _093_ (
    .A(s[1]),
    .B(_012_),
    .C(_039_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a31oi_1 _094_ (
    .A1(_022_),
    .A2(_026_),
    .A3(_038_),
    .B1(_040_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(_036_),
    .A2(_037_),
    .B1(_041_),
    .Y(y[1])
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(s[0]),
    .B(s[1]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o22ai_1 _097_ (
    .A1(s[1]),
    .A2(_014_),
    .B1(_015_),
    .B2(_042_),
    .Y(y[0])
  );
  sky130_fd_sc_hd__nor2_1 _098_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _099_ (
    .A(b[4]),
    .B(a[4]),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2b_1 _100_ (
    .A_N(b[3]),
    .B(a[3]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__o21ai_0 _101_ (
    .A1(_007_),
    .A2(_019_),
    .B1(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _102_ (
    .A(_044_),
    .B(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(_020_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__maj3_1 _104_ (
    .A(b[3]),
    .B(a[3]),
    .C(_025_),
    .X(_049_)
  );
  sky130_fd_sc_hd__o21ai_0 _105_ (
    .A1(_044_),
    .A2(_049_),
    .B1(_026_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__a21oi_1 _106_ (
    .A1(_044_),
    .A2(_049_),
    .B1(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a21oi_1 _107_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(s[0]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor3_1 _108_ (
    .A(s[1]),
    .B(_043_),
    .C(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__or3_1 _109_ (
    .A(_048_),
    .B(_051_),
    .C(_053_),
    .X(y[4])
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(y[3]),
    .A1(out_reg[3]),
    .S(sync),
    .X(out[3])
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(y[2]),
    .A1(out_reg[2]),
    .S(sync),
    .X(out[2])
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(y[1]),
    .A1(out_reg[1]),
    .S(sync),
    .X(out[1])
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(y[0]),
    .A1(out_reg[0]),
    .S(sync),
    .X(out[0])
  );
  sky130_fd_sc_hd__nand2b_1 _114_ (
    .A_N(out_reg[4]),
    .B(sync),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o41a_1 _115_ (
    .A1(sync),
    .A2(_048_),
    .A3(_051_),
    .A4(_053_),
    .B1(_054_),
    .X(out[4])
  );
  sky130_fd_sc_hd__clkinv_1 _116_ (
    .A(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _117_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _118_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _119_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(clk),
    .D(y[0]),
    .Q(out_reg[0]),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk),
    .D(y[1]),
    .Q(out_reg[1]),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk),
    .D(y[2]),
    .Q(out_reg[2]),
    .RESET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk),
    .D(y[3]),
    .Q(out_reg[3]),
    .RESET_B(_000_)
  );
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk),
    .D(y[4]),
    .Q(out_reg[4]),
    .RESET_B(_004_)
  );
endmodule
