/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module Lut(a, b, clk, reset, s, sync, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  input clk;
  wire clk;
  output [4:0] out;
  wire [4:0] out;
  wire \out_reg[0] ;
  wire \out_reg[1] ;
  wire \out_reg[2] ;
  wire \out_reg[3] ;
  wire \out_reg[4] ;
  input reset;
  wire reset;
  input [1:0] s;
  wire [1:0] s;
  input sync;
  wire sync;
  wire \y[0] ;
  wire \y[1] ;
  wire \y[2] ;
  wire \y[3] ;
  wire \y[4] ;
  sky130_fd_sc_hd__clkinv_1 _052_ (
    .A(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__clkinv_1 _053_ (
    .A(sync),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _054_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__o22ai_1 _055_ (
    .A1(s[0]),
    .A2(s[1]),
    .B1(b[0]),
    .B2(a[0]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__mux2i_1 _056_ (
    .A0(s[1]),
    .A1(_007_),
    .S(_006_),
    .Y(\y[0] )
  );
  sky130_fd_sc_hd__mux2_1 _057_ (
    .A0(\out_reg[0] ),
    .A1(\y[0] ),
    .S(_005_),
    .X(out[0])
  );
  sky130_fd_sc_hd__nor2_1 _058_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _059_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _060_ (
    .A(b[1]),
    .B(a[1]),
    .X(_010_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _061_ (
    .A(s[1]),
    .SLEEP(s[0]),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _062_ (
    .A(_006_),
    .B(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__a21oi_1 _063_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(s[0]),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _064_ (
    .A(s[1]),
    .B(_008_),
    .C(_013_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _065_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand2_1 _066_ (
    .A(s[0]),
    .B(s[1]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor2_1 _067_ (
    .A(_010_),
    .B(_015_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__xnor2_1 _068_ (
    .A(_010_),
    .B(_015_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _069_ (
    .A1(_011_),
    .A2(_012_),
    .B1(_014_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__o21ai_0 _070_ (
    .A1(_016_),
    .A2(_018_),
    .B1(_019_),
    .Y(\y[1] )
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(\out_reg[1] ),
    .A1(\y[1] ),
    .S(_005_),
    .X(out[1])
  );
  sky130_fd_sc_hd__nor2_1 _072_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _073_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(_006_),
    .A2(_008_),
    .B1(_009_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__xnor2_1 _075_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a21oi_1 _076_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(s[0]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor3_1 _077_ (
    .A(s[1]),
    .B(_020_),
    .C(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _078_ (
    .A(a[1]),
    .SLEEP(b[1]),
    .X(_026_)
  );
  sky130_fd_sc_hd__o21a_1 _079_ (
    .A1(_017_),
    .A2(_026_),
    .B1(_021_),
    .X(_027_)
  );
  sky130_fd_sc_hd__nor3_1 _080_ (
    .A(_017_),
    .B(_021_),
    .C(_026_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _081_ (
    .A(_016_),
    .B(_027_),
    .C(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a211o_1 _082_ (
    .A1(_011_),
    .A2(_023_),
    .B1(_025_),
    .C1(_029_),
    .X(\y[2] )
  );
  sky130_fd_sc_hd__mux2_1 _083_ (
    .A0(\out_reg[2] ),
    .A1(\y[2] ),
    .S(_005_),
    .X(out[2])
  );
  sky130_fd_sc_hd__nor2_1 _084_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__xnor2_1 _085_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _086_ (
    .A(a[2]),
    .SLEEP(b[2]),
    .X(_032_)
  );
  sky130_fd_sc_hd__o21a_1 _087_ (
    .A1(_027_),
    .A2(_032_),
    .B1(_031_),
    .X(_033_)
  );
  sky130_fd_sc_hd__nor3_1 _088_ (
    .A(_027_),
    .B(_031_),
    .C(_032_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nor3_1 _089_ (
    .A(_016_),
    .B(_033_),
    .C(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a21oi_1 _090_ (
    .A1(b[3]),
    .A2(a[3]),
    .B1(s[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor3_1 _091_ (
    .A(s[1]),
    .B(_030_),
    .C(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__maj3_1 _092_ (
    .A(b[2]),
    .B(a[2]),
    .C(_022_),
    .X(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _093_ (
    .A(_031_),
    .B(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__a211o_1 _094_ (
    .A1(_011_),
    .A2(_039_),
    .B1(_037_),
    .C1(_035_),
    .X(\y[3] )
  );
  sky130_fd_sc_hd__mux2_1 _095_ (
    .A0(\out_reg[3] ),
    .A1(\y[3] ),
    .S(_005_),
    .X(out[3])
  );
  sky130_fd_sc_hd__nor2_1 _096_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(a[3]),
    .SLEEP(b[3]),
    .X(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _099_ (
    .A1(_033_),
    .A2(_042_),
    .B1(_041_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or3_1 _100_ (
    .A(_033_),
    .B(_041_),
    .C(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand4_1 _101_ (
    .A(s[0]),
    .B(s[1]),
    .C(_043_),
    .D(_044_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__maj3_1 _102_ (
    .A(b[3]),
    .B(a[3]),
    .C(_038_),
    .X(_046_)
  );
  sky130_fd_sc_hd__xnor2_1 _103_ (
    .A(_041_),
    .B(_046_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_1 _104_ (
    .A(_011_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _105_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(s[0]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__or3_1 _106_ (
    .A(s[1]),
    .B(_040_),
    .C(_049_),
    .X(_050_)
  );
  sky130_fd_sc_hd__nand3_1 _107_ (
    .A(_045_),
    .B(_048_),
    .C(_050_),
    .Y(\y[4] )
  );
  sky130_fd_sc_hd__nor2_1 _108_ (
    .A(_005_),
    .B(\out_reg[4] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__a41oi_1 _109_ (
    .A1(_005_),
    .A2(_045_),
    .A3(_048_),
    .A4(_050_),
    .B1(_051_),
    .Y(out[4])
  );
  sky130_fd_sc_hd__clkinv_1 _110_ (
    .A(reset),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _111_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _112_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _113_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _114_ (
    .CLK(clk),
    .D(\y[0] ),
    .Q(\out_reg[0] ),
    .RESET_B(_000_)
  );
  sky130_fd_sc_hd__dfrtp_1 _115_ (
    .CLK(clk),
    .D(\y[1] ),
    .Q(\out_reg[1] ),
    .RESET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_1 _116_ (
    .CLK(clk),
    .D(\y[2] ),
    .Q(\out_reg[2] ),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(clk),
    .D(\y[3] ),
    .Q(\out_reg[3] ),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(clk),
    .D(\y[4] ),
    .Q(\out_reg[4] ),
    .RESET_B(_004_)
  );
endmodule
