/*
    Automatically generated by Fault
    Do not modify.
    Generated on: 2026-05-05 13:24:01
*/
`include "custom_cells.v"
`include "netlist.v.chained.v"


`ifndef CLOCK_PERIOD
    `define CLOCK_PERIOD 4
`endif

module testbench;
    reg[0:0] \tck ;
    reg[0:0] \test ;
    reg[0:0] \reset ;
    reg[0:0] \shift ;
    reg[0:0] \_118_ ;
    wire[0:0] \sout ;
    reg[0:0] \_115_ ;
    reg[0:0] \_114_ ;
    wire[4:0] \out ;
    reg[0:0] \sync ;
    reg[0:0] \clk ;
    reg[4:0] \a ;
    reg[4:0] \b ;
    wire[0:0] \_116_.d ;
    reg[0:0] \_117_ ;
    reg[0:0] \_116_ ;
    wire[0:0] \_117_.d ;
    wire[0:0] \_118_.d ;
    reg[1:0] \s ;
    wire[0:0] \_114_.d ;
    wire[0:0] \_115_.d ;
    reg[0:0] \sin ;

        always #(`CLOCK_PERIOD / 2) clk = ~clk; 
        always #(`CLOCK_PERIOD / 2) tck = ~tck; 

    Lut uut(
        .\tck ( \tck ) , .\test ( \test ) , .\reset ( \reset ) , .\shift ( \shift ) , .\_118_ ( \_118_ ) , .\sout ( \sout ) , .\_115_ ( \_115_ ) , .\_114_ ( \_114_ ) , .\out ( \out ) , .\sync ( \sync ) , .\clk ( \clk ) , .\a ( \a ) , .\b ( \b ) , .\_116_.d ( \_116_.d ) , .\_117_ ( \_117_ ) , .\_116_ ( \_116_ ) , .\_117_.d ( \_117_.d ) , .\_118_.d ( \_118_.d ) , .\s ( \s ) , .\_114_.d ( \_114_.d ) , .\_115_.d ( \_115_.d ) , .\sin ( \sin ) 
    ); 

    wire[27:0] __serializable__ =
        28'b0010011111000100000010111001;
    reg[27:0] __serial__;
    integer i;
    initial begin
        `ifdef VCD
            $dumpfile("chain.vcd");
            $dumpvars(0, testbench);
        `endif
        \a = 0 ;
        \b = 0 ;
        \clk = 0 ;
        \reset = 1 ;
        \s = 0 ;
        \sync = 0 ;
        \_114_ = 0 ;
        \_115_ = 0 ;
        \_116_ = 0 ;
        \_117_ = 0 ;
        \_118_ = 0 ;
        \sin = 0 ;
        \shift = 0 ;
        \tck = 0 ;
        \test = 0 ;

        #(`CLOCK_PERIOD*5);
        reset = ~reset;
        shift = 1;
        test = 1;
        for (i = 0; i < 28; i = i + 1) begin
            sin = __serializable__[i];
            #(`CLOCK_PERIOD);
        end
        for (i = 0; i < 28; i = i + 1) begin
            __serial__[i] = sout;
            #(`CLOCK_PERIOD);
        end
        if (__serializable__ === __serial__) begin
            $display("Success: expected %b got %b", __serializable__, __serial__);
            $display("SUCCESS_STRING");
        end else begin
            $display("Failed: expected %b got %b", __serializable__, __serial__);
        end
        $finish;
    end
endmodule
